### ISSUE TITLE
Hardcoded Conda Version

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pmgr#1]
Any reason we are hard-coding the conda version here? This will not get new updates to the environment as written. Just `/reg/g/pcds/pyps/conda/py36env.sh` should always be the latest?

https://github.com/pcdshub/pmgr/blob/212056bf86e1fbe703e513fbf77f62f483829d29/pmgrUtils.sh#L7

**Comment by ZLLentz** [comment]
Linking to latest is dangerous and liable to break as latest changes.

**Comment by teddyrendahl** [comment]
I think the ultimate answer is we should be packaging shell scripts with the packages they belong in. Going this route guarantees you to be synced. I just don't want to have to crawl around through all these files when we release a new environment with a bug fix.

**Comment by ZLLentz** [comment]
100% agree, moving towards packaging is the correct solution

**Comment by mcb64** [comment]
Plus, I think there was an issue with the standard environment, but I forget the details.  (I think pmgr needed an extra package or something.  It certainly needed a Qt5 patch.)
