### ISSUE TITLE
Add pyqt version check when running the GUI

### ISSUE THREAD

**Issue by klauer** [pcdshub/pmgr#10]
5.6-slac is required. GUI will segfault without this version.

https://github.com/pcdshub/pcds-recipes/blob/master/pyqt/post_init.patch

**Comment by klauer** [comment]
(It's unlikely this will ever get fixed, but rather just shelved or rewritten.)

**Comment by mcb64** [comment]
Hmm.  I switched to the conda pcds-4.0.1 environment (which is using Qt 5.12.9) and this seems to be working.  Are we still applying that SLAC patch, or did someone in the Qt or PyQt community blink?

**Comment by klauer** [comment]
Interesting - I haven't tried this since finding out about the custom qt patch/version. Glad to hear the latest update doesn't depend on it!

**Comment by mcb64** [comment]
Ken, since this works with regular qt releases now, I think we can just close this issue... what do you think?

**Comment by klauer** [comment]
Trying to refresh my own memory - looks like we had a Slack discussion about this in March of last year (why the patch was necessary, and saying pmgr will almost certainly crash without it due to the signal implementation, etc. etc.). Solution was "just let pmgr live in its own environment with its patched pyqt, if you want the GUI" or something along those lines.

If the above is unnecessary in your testing, that's amazing in my book. Let's close this then. 👍
