### ISSUE TITLE
usr missing from pmgrUtils.cfg

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pmgr#4]
We need to do one of:
- add usr to pmgrUtils.cfg
- stop checking two separate files (pmgrUtils.py, pmgrUtils.cfg) for the hutch list
- stop using the hutch list at all
- find a way to make the list not hard-coded

**Comment by ZLLentz** [comment]
follow-up to changes @rajanplumley pushed earlier

**Comment by mcb64** [comment]
At this point, I've killed pmgrUtils.py.  In any event, even if we resurrect this, the correct thing to do would be to look at pmgrobj.getHutchList() to get the list of hutches actually set up for parameter manager use.

Closing.
