### ISSUE TITLE
Launch script interferes with user launch scripts

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pmgr#5]
The base `pmgr` launch script bundled when this module is installed will interfere with the user's defined `pmgr` aliases if you activate the conda environment after adding the user aliases to your path.

Some choices:
1. Provided `pmgr` script should work like the standard aliases:
```
#!/bin/bash
HUTCH=`get_info --gethutch`
/reg/g/pcds/pyps/config/${HUTCH}/pmgr/pmgr --type ims_motor --hutch ${HUTCH} $@ &
```
pros: everything is well-contained in one place
cons: still conflicts with alias, needs to be updated if we add a new type
2. Rename the `pmgr` script and adjust alias accordingly
pros: minimal changes
cons: awkward
3. Restore old structure just a little bit

I'm not really sure, there may be a better option

**Comment by mcb64** [comment]
How to install this standalone is sort of an open question.  I've been tagging the git, checking it out into my area, and then running "do_release /reg/g/pcds/pyps/apps/pmgr/$VERSION", which does an install into the specified directory and makes a top-level pmgr script that sets up the environment and then runs the installed script.  

Then the provided script in /reg/g/pcds/pyps/config/$HUTCH/pmgr looks like what Zach posted.

This doesn't feel optimal, but I'm open to suggestions.

**Comment by mcb64** [comment]
Should the installed pmgr script just be renamed?  Say to pmgr_run.sh or pmgr_gui.sh?  Then if you are using conda and an alias for pmgr, you are fine.  My do_release still installs a pmgr script, but it's not on anyone's path and runs pmgr_run.sh/pmgr_gui.sh.  If someone puts /reg/g/pcds/pyps/config/$HUTCH on their path, they are still fine, because pmgr.sh there doesn't conflict with anything.

**Comment by mcb64** [comment]
Changed the conda entry point script to be pmgrLauncher.sh.  The do_release script will still make a pmgr script (which is run by /reg/g/pcds/pyps/config/$HUTCH/pmgr.sh) but this shouldn't be on anyone's path, so life is good.
