### ISSUE TITLE
Apply configs to PV base not in database

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pmgr#6]
For dumb motors and new motors it'd be nice to be able to skip having the stage in the database.

Would need to add something like pmgrobj.apply_config that instead takes a PV base and a config id

**Comment by mcb64** [comment]
Or perhaps we should add a quick function to add a new motor?

**Comment by mcb64** [comment]
I've implemented the ability to apply without having a motor entry.

**Comment by ZLLentz** [comment]
I don't even remember writing this one! 2018 seems like a different era.
